In [53]:
import warnings
warnings.filterwarnings("ignore")

# CMD command

1. __initialise config file download from spacy website__  
python -m spacy init fill-config ./base_config.cfg ./config.cfg

2. __convert .pickle to .spacy__  
python .\preprocess.py  

3. __train NER model__  
python -m spacy train .\config.cfg --output .\output\ --paths.train .\data\train.spacy --paths.dev .\data\test.spacy

In [1]:
import numpy as np
import pandas as pd
import cv2
import pytesseract
from glob import glob
import spacy
import re
import string

In [2]:
def cleanText(txt):
    whitespace = string.whitespace
    punctuation = '!#$%&\'()*+:;<=>?[\\]^`{|}~'
    tableWhitespace = str.maketrans('','',whitespace)
    tablePunctuation = str.maketrans('','',punctuation)
    text = str(txt)
    text = text.lower()
    removewhitespace = text.translate(tableWhitespace)
    removepunctuation = removewhitespace.translate(tablePunctuation)
    
    return str(removepunctuation)

In [3]:
# Load NER model
model_ner = spacy.load('./output/model-best/')

In [4]:
# Load Image
image = cv2.imread('./data/6.jpg')

# cv2.imshow('businesscard',image)
# cv2.waitKey(0)
# cv2.destroyAllWindows

# Extract data using Pytesseract
tessData = pytesseract.image_to_data(image)

# convert into dataframe
tessList = list(map(lambda x: x.split('\t'), tessData.split('\n')))
df = pd.DataFrame(tessList[1:],columns=tessList[0])
df.dropna(inplace=True) # drop missing values
df['text'] = df['text'].apply(cleanText)


# Convert data into content
df_clean = df.query('text != "" ') #not equal to empty space
content = " ".join([w for w in df_clean['text']])
print(content)


# Get prediction from NER model
doc = model_ner(content)

cell 8099948528 ga 8466045457 email lictsrikant@gmail.com life insurance corporation of india seosrika ntht@gmail “com thathineni srikanth insurance advisor agent code no. 0316164y life insurance corporation of india br. off. lic office, trimulgherry, sec’bad - 500 016. add. borabanda, hyderabad - 500 018. lictsrikant8099948528.blogspot.in, interviewsinhyderabad.blogspot.in facebook.com/lictsrikant8099948528, facebook.com/thathineni.srikanth.9 promote your business online pybo

In [5]:
from spacy import displacy

In [6]:
# Method 1

displacy.serve(doc,style='ent')

D:\OCR\Udemy-OCR\docuscan\lib\site-packages\spacy\displacy\__init__.py:103: UserWarning: [W011] It looks like you're calling displacy.serve from within a Jupyter notebook or a similar environment. This likely means you're already running a local web server, so there's no need to make displaCy start another one. Instead, you should be able to replace displacy.serve with displacy.render to show the visualization.
  warnings.warn(Warnings.W011)

Using the 'ent' visualizer
Serving on http://0.0.0.0:5000 ...

Shutting down server on port 5000.

In [7]:
# Method 2

displacy.render(doc,style='ent')

# Tagging

In [10]:
# 36.Tagging Each Word

docjson = doc.to_json()
docjson.keys()  #ents: prediction results - label of words   ;   tokens: each words

dict_keys(['text', 'ents', 'tokens'])

In [12]:
docjson['ents']

[{'start': 5, 'end': 15, 'label': 'B-PHONE'},
 {'start': 19, 'end': 29, 'label': 'B-PHONE'},
 {'start': 36, 'end': 57, 'label': 'B-EMAIL'},
 {'start': 58, 'end': 62, 'label': 'B-ORG'},
 {'start': 63, 'end': 72, 'label': 'I-ORG'},
 {'start': 73, 'end': 84, 'label': 'I-ORG'},
 {'start': 85, 'end': 87, 'label': 'I-ORG'},
 {'start': 88, 'end': 93, 'label': 'I-ORG'},
 {'start': 94, 'end': 102, 'label': 'B-EMAIL'},
 {'start': 103, 'end': 113, 'label': 'I-EMAIL'},
 {'start': 114, 'end': 115, 'label': 'I-EMAIL'},
 {'start': 115, 'end': 118, 'label': 'I-EMAIL'},
 {'start': 119, 'end': 129, 'label': 'B-NAME'},
 {'start': 130, 'end': 138, 'label': 'I-NAME'},
 {'start': 139, 'end': 148, 'label': 'B-DES'},
 {'start': 149, 'end': 156, 'label': 'I-DES'},
 {'start': 181, 'end': 185, 'label': 'B-ORG'},
 {'start': 186, 'end': 195, 'label': 'I-ORG'},
 {'start': 196, 'end': 207, 'label': 'I-ORG'},
 {'start': 208, 'end': 210, 'label': 'I-ORG'},
 {'start': 211, 'end': 216, 'label': 'I-ORG'},
 {'start': 343, 'end': 376, 'label': 'B-WEB'}]

In [20]:
doc_text = docjson['text']

In [28]:
dataframe_tokens = pd.DataFrame(docjson['tokens'])
dataframe_tokens['token'] = dataframe_tokens[['start','end']].apply(
    lambda x: doc_text[x[0]:x[1]], axis=1)

dataframe_tokens.head(10)

   id  start  end                  token
0   0      0    4                   cell
1   1      5   15             8099948528
2   2     16   18                     ga
3   3     19   29             8466045457
4   4     30   35                  email
5   5     36   57  lictsrikant@gmail.com
6   6     58   62                   life
7   7     63   72              insurance
8   8     73   84            corporation
9   9     85   87                     of

In [30]:
# 37. Join label to tokens dataframe
right_table = pd.DataFrame(docjson['ents'])[['start','label']]
dataframe_tokens = pd.merge(dataframe_tokens, right_table, how='left', on='start')

In [31]:
dataframe_tokens.fillna('O', inplace=True)
dataframe_tokens.head(10)

   id  start  end                  token    label
0   0      0    4                   cell        O
1   1      5   15             8099948528  B-PHONE
2   2     16   18                     ga        O
3   3     19   29             8466045457  B-PHONE
4   4     30   35                  email        O
5   5     36   57  lictsrikant@gmail.com  B-EMAIL
6   6     58   62                   life    B-ORG
7   7     63   72              insurance    I-ORG
8   8     73   84            corporation    I-ORG
9   9     85   87                     of    I-ORG

In [42]:
#38. Join token dataframe with Pytesseract

df_clean['end'] = df_clean['text'].apply(lambda x: len(x)+1).cumsum() - 1
df_clean['start'] = df_clean[['text','end']].apply(lambda x: x[1] - len(x[0]), axis = 1)

C:\Users\A22801\AppData\Local\Temp\ipykernel_5720\3501085372.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['end'] = df_clean['text'].apply(lambda x: len(x)+1).cumsum() - 1
C:\Users\A22801\AppData\Local\Temp\ipykernel_5720\3501085372.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['start'] = df_clean[['text','end']].apply(lambda x: x[1] - len(x[0]), axis = 1)

In [43]:
# inner join with start
dataframe_info = pd.merge(df_clean, dataframe_tokens[['start','token','label']], how='inner', on='start')

In [45]:
dataframe_info.tail(10)

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text,end,start,token,label
41,5,1,6,3,1,6,495,474,53,21,96.027008,018.,307,303,018,O
42,5,1,6,3,2,1,46,506,430,27,85.618164,"lictsrikant8099948528.blogspot.in,",342,308,lictsrikant8099948528.blogspot.in,O
43,5,1,6,3,2,2,488,506,429,27,89.912384,interviewsinhyderabad.blogspot.in,376,343,interviewsinhyderabad.blogspot.in,B-WEB
44,5,1,6,3,3,1,44,539,472,25,87.967415,"facebook.com/lictsrikant8099948528,",412,377,facebook.com/lictsrikant8099948528,O
45,5,1,6,3,3,2,526,539,443,22,90.545654,facebook.com/thathineni.srikanth.9,447,413,facebook.com/thathineni.srikanth.9,O
46,5,1,6,3,4,1,46,571,106,21,96.344551,promote,455,448,promote,O
47,5,1,6,3,4,2,161,576,56,22,95.835091,your,460,456,your,O
48,5,1,6,3,4,3,226,571,111,21,96.409111,business,469,461,business,O
49,5,1,6,3,4,4,347,571,74,21,93.162605,online,476,470,online,O
50,5,1,6,3,4,5,432,571,96,27,92.261208,pybo,481,477,pybo,O

# Bounding Box

In [32]:
df_clean

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
12,5,1,3,1,1,1,722,53,64,28,90.167198,cell
14,5,1,3,1,1,3,822,53,203,28,96.483879,8099948528
17,5,1,3,2,1,1,55,55,85,89,47.185547,ga
18,5,1,3,2,1,2,822,95,203,28,96.435081,8466045457
20,5,1,3,2,2,1,593,136,93,25,89.289780,email
22,5,1,3,2,2,3,709,136,316,31,86.249245,lictsrikant@gmail.com
25,5,1,3,3,1,1,46,170,33,14,96.406654,life
26,5,1,3,3,1,2,85,151,92,42,95.806709,insurance
27,5,1,3,3,1,3,183,170,117,14,96.909729,corporation
28,5,1,3,3,1,4,306,170,20,14,96.172005,of
29,5,1,3,3,1,5,332,170,42,14,96.796776,india
30,5,1,3,3,1,6,668,166,119,37,92.970848,seosrika
31,5,1,3,3,1,7,791,165,162,44,91.918060,ntht@gmail
32,5,1,3,3,1,8,958,180,67,19,7.601662,“com
36,5,1,4,1,1,1,310,228,232,30,92.664276,thathineni
37,5,1,4,1,1,2,557,227,198,32,96.249886,srikanth
41,5,1,5,1,1,1,399,271,147,25,96.546059,insurance
42,5,1,5,1,1,2,555,271,114,25,96.382957,advisor
44,5,1,5,1,2,1,328,310,89,31,96.594261,agent
45,5,1,5,1,2,2,428,310,80,25,96.651688,code
46,5,1,5,1,2,3,521,310,48,25,92.426491,no.
47,5,1,5,1,2,4,582,310,155,25,91.050606,0316164y
51,5,1,6,1,1,1,47,396,83,30,96.843925,life
52,5,1,6,1,1,2,145,395,236,32,96.428986,insurance
53,5,1,6,1,1,3,395,395,296,32,96.263168,corporation
54,5,1,6,1,1,4,706,395,53,32,95.340492,of
55,5,1,6,1,1,5,775,396,107,30,95.340492,india
58,5,1,6,2,1,1,45,441,36,21,96.699669,br.
59,5,1,6,2,1,2,93,441,45,22,96.615921,off.
60,5,1,6,2,1,3,149,441,42,22,96.824722,lic
61,5,1,6,2,1,4,201,441,79,25,93.299294,"office,"
62,5,1,6,2,1,5,290,441,163,27,91.747375,"trimulgherry,"
63,5,1,6,2,1,6,465,441,101,22,92.451996,sec’bad
64,5,1,6,2,1,7,576,453,8,3,91.897362,-
65,5,1,6,2,1,8,594,441,46,21,96.442276,500
66,5,1,6,2,1,9,650,441,53,22,95.835518,016.
69,5,1,6,3,1,1,44,474,62,21,93.283730,add.
70,5,1,6,3,1,2,118,474,144,25,92.916100,"borabanda,"
71,5,1,6,3,1,3,275,474,136,27,93.280846,hyderabad
72,5,1,6,3,1,4,422,486,8,3,93.201012,-
73,5,1,6,3,1,5,440,474,45,21,96.027008,500
74,5,1,6,3,1,6,495,474,53,21,96.027008,018.
76,5,1,6,3,2,1,46,506,430,27,85.618164,"lictsrikant8099948528.blogspot.in,"
77,5,1,6,3,2,2,488,506,429,27,89.912384,interviewsinhyderabad.blogspot.in
79,5,1,6,3,3,1,44,539,472,25,87.967415,"facebook.com/lictsrikant8099948528,"
80,5,1,6,3,3,2,526,539,443,22,90.545654,facebook.com/thathineni.srikanth.9
82,5,1,6,3,4,1,46,571,106,21,96.344551,promote
83,5,1,6,3,4,2,161,576,56,22,95.835091,your
84,5,1,6,3,4,3,226,571,111,21,96.409111,business
85,5,1,6,3,4,4,347,571,74,21,93.162605,online
86,5,1,6,3,4,5,432,571,96,27,92.261208,pybo

In [60]:
#39. Bounding Box and Tagging Predicted Entities
bb_df = dataframe_info.query("label != 'O' ")
img = image.copy()

for x,y,w,h,label in bb_df[['left','top','width','height','label']].values:
    x = int(x)
    y = int(y)
    w = int(w)
    h = int(h)
    
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.putText(img,str(label),(x,y),cv2.FONT_HERSHEY_PLAIN,1,(255,0,0),2)

cv2.imshow("Predictions", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [61]:
#40. Combine the BIO information
bb_df['label'] = bb_df['label'].apply(lambda x: x[2:])
bb_df.head()

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text,end,start,token,label
1,5,1,3,1,1,3,822,53,203,28,96.483879,8099948528,15,5,8099948528,PHONE
3,5,1,3,2,1,2,822,95,203,28,96.435081,8466045457,29,19,8466045457,PHONE
5,5,1,3,2,2,3,709,136,316,31,86.249245,lictsrikant@gmail.com,57,36,lictsrikant@gmail.com,EMAIL
6,5,1,3,3,1,1,46,170,33,14,96.406654,life,62,58,life,ORG
7,5,1,3,3,1,2,85,151,92,42,95.806709,insurance,72,63,insurance,ORG

In [62]:
# group the label 
class groupgen():
    def __init__(self):
        self.id = 0
        self.text = ''
    
    def getgroup(self,text):
        if self.text == text:
            return self.id
        else:
            self.id += 1
            self.text = text
            return self.id

grp_gen = groupgen()

In [63]:
bb_df['group'] = bb_df['label'].apply(grp_gen.getgroup)
bb_df

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text,end,start,token,label,group
1,5,1,3,1,1,3,822,53,203,28,96.483879,8099948528,15,5,8099948528,PHONE,1
3,5,1,3,2,1,2,822,95,203,28,96.435081,8466045457,29,19,8466045457,PHONE,1
5,5,1,3,2,2,3,709,136,316,31,86.249245,lictsrikant@gmail.com,57,36,lictsrikant@gmail.com,EMAIL,2
6,5,1,3,3,1,1,46,170,33,14,96.406654,life,62,58,life,ORG,3
7,5,1,3,3,1,2,85,151,92,42,95.806709,insurance,72,63,insurance,ORG,3
8,5,1,3,3,1,3,183,170,117,14,96.909729,corporation,84,73,corporation,ORG,3
9,5,1,3,3,1,4,306,170,20,14,96.172005,of,87,85,of,ORG,3
10,5,1,3,3,1,5,332,170,42,14,96.796776,india,93,88,india,ORG,3
11,5,1,3,3,1,6,668,166,119,37,92.970848,seosrika,102,94,seosrika,EMAIL,4
12,5,1,3,3,1,7,791,165,162,44,91.918060,ntht@gmail,113,103,ntht@gmail,EMAIL,4
13,5,1,3,3,1,8,958,180,67,19,7.601662,“com,118,114,“,EMAIL,4
14,5,1,4,1,1,1,310,228,232,30,92.664276,thathineni,129,119,thathineni,NAME,5
15,5,1,4,1,1,2,557,227,198,32,96.249886,srikanth,138,130,srikanth,NAME,5
16,5,1,5,1,1,1,399,271,147,25,96.546059,insurance,148,139,insurance,DES,6
17,5,1,5,1,1,2,555,271,114,25,96.382957,advisor,156,149,advisor,DES,6
22,5,1,6,1,1,1,47,396,83,30,96.843925,life,185,181,life,ORG,7
23,5,1,6,1,1,2,145,395,236,32,96.428986,insurance,195,186,insurance,ORG,7
24,5,1,6,1,1,3,395,395,296,32,96.263168,corporation,207,196,corporation,ORG,7
25,5,1,6,1,1,4,706,395,53,32,95.340492,of,210,208,of,ORG,7
26,5,1,6,1,1,5,775,396,107,30,95.340492,india,216,211,india,ORG,7
43,5,1,6,3,2,2,488,506,429,27,89.912384,interviewsinhyderabad.blogspot.in,376,343,interviewsinhyderabad.blogspot.in,WEB,8

In [64]:
# right and bottom of bounding box
bb_df[['left','top','width','height']] = bb_df[['left','top','width','height']].astype(int)
bb_df['right'] = bb_df['left'] + bb_df['width']
bb_df['bottom'] = bb_df['top'] + bb_df['height']

In [75]:
bb_df.head()

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text,end,start,token,label,group,right,bottom
1,5,1,3,1,1,3,822,53,203,28,96.483879,8099948528,15,5,8099948528,PHONE,1,1025,81
3,5,1,3,2,1,2,822,95,203,28,96.435081,8466045457,29,19,8466045457,PHONE,1,1025,123
5,5,1,3,2,2,3,709,136,316,31,86.249245,lictsrikant@gmail.com,57,36,lictsrikant@gmail.com,EMAIL,2,1025,167
6,5,1,3,3,1,1,46,170,33,14,96.406654,life,62,58,life,ORG,3,79,184
7,5,1,3,3,1,2,85,151,92,42,95.806709,insurance,72,63,insurance,ORG,3,177,193

In [76]:
# tagging: groupby group
col_group = ['left','top','right','bottom','label','token','group']
group_tag_img = bb_df[col_group].groupby(by='group')

In [77]:
img_tagging = group_tag_img.agg({
    
    'left':min,
    'right':max,
    'top':min,
    'bottom':max,
    'label':np.unique,
    'token':lambda x: " ".join(x)
    
})

In [78]:
img_tagging

       left  right  top  bottom    label                                token
group
1       822   1025   53     123  [PHONE]                8099948528 8466045457
2       709   1025  136     167  [EMAIL]                lictsrikant@gmail.com
3        46    374  151     193    [ORG]  life insurance corporation of india
4       668   1025  165     209  [EMAIL]                seosrika ntht@gmail “
5       310    755  227     259   [NAME]                  thathineni srikanth
6       399    669  271     296    [DES]                    insurance advisor
7        47    882  395     427    [ORG]  life insurance corporation of india
8       488    917  506     533    [WEB]    interviewsinhyderabad.blogspot.in

In [79]:
#39. Bounding Box and Tagging Predicted Entities
img_bb = image.copy()

for l,r,t,b,label,token in img_tagging.values:
    
    
    cv2.rectangle(img_bb,(l,t),(r,b),(0,255,0),2)
    cv2.putText(img_bb,str(label),(l,t),cv2.FONT_HERSHEY_PLAIN,1,(255,0,0),2)

cv2.imshow("Bounding Box BusinessCard", img_bb)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Parser

In [80]:
# 42. Parsing Function
def parser(text,label):
    if label == 'PHONE':
        text = text.lower()
        text = re.sub(r'\D', '', text)
    
    elif label == 'EMAIL':
        text = text.lower()
        allow_special_char = '@_.-'
        text = re.sub(r'[^A-Za-z0-9{} ]'.format(allow_special_char), '', text)
    
    elif label == 'WEB':
        text = text.lower()
        allow_special_char = ':/.%#-'
        text = re.sub(r'[^A-Za-z0-9{} ]'.format(allow_special_char), '', text)
        
    elif label in ('NAME', 'DES'):
        text = text.lower()
        text = re.sub(r'[^a-z ]', '', text)
        text = text.title()
        
    elif label == 'ORG':
        text = text.lower()
        text = re.sub(r'[^a-z0-9 ]', '', text)
        text = text.title()       
    
    return text

In [81]:
# 43. Testing
parser('Srikanth 1896196', 'NAME')

'1896196'